### ISSUE TITLE
问个问题..

### ISSUE THREAD

**Issue by hanxuan123** [xhjcehust/LFTPool#2]
大佬，想问下这句话如何理解额 对于主线程放入工作和工作线程取出任务的竞争问题，可以采取环形队列的方式避免。 这里主线程插入任务的时候不是向指定pid线程发送信号，然后对应工作线程执行对应任务码，存在什么竞争额不太理解额。 
还有是否如果没有任务迁移是否就可以不用在迁出工作使用原子操作比较了 
还有这里负载均衡算法是要自己设计吗，然后在合适的时候选择是否增加或者减少线程 
还有这个线程池和普通的用互斥量和条件变量的线程池是在什么样的场景下有性能提升额 .....抱歉一下子问了这么多问题....

**Comment by xhjcehust** [comment]
1.一旦工作线程被唤醒，会一直从队列取出任务，而主线程在不断往队列放入任务，相当于两个线程同时操作队列，存在竞争操作
2.如果没有任务迁移可以不用在迁出工作使用原子操作比较
3.提供的默认负载均衡算法Round-Robin和Least-Load不满足需求的话可以重新自己设计
4.无锁线程池在任务执行时间较短，工作线程较多，竞争比较激烈的场景下性能比互斥量和条件变量的线程池要高
