### ISSUE TITLE
方案没问题，代码有问题

### ISSUE THREAD

**Issue by AngusLkc** [xhjcehust/LFTPool#3]
这个代码有问题，在处理完任务队列内的任务后下一轮循环调用sigwait前，这中间如果主线程往任务线程发送了SIGUSR1信号，那么任务线程就会调用信号处理函数，而这时任务队列非空，下一轮循环的sigwait调用将会一直阻塞等待主线程的通知。
个人认为，线程在处理任务时不应该恢复SIGUSR1信号为异步方式，如果在任务处理周期内收到了一个或多个SIGUSR1信号，未决信号队列只会保留一个SIGUSR1信号，则最多只会导致"while (thread_queue_empty(thread) && !thread->shutdown)"循环空转一轮，但是能使每一个任务都及时的处理。

**Comment by xhjcehust** [comment]
代码的问题欢迎提交pr共同完善
